import CardsSection from '@/components/CardsSection'
import Footer from '@/components/Footer'
import Services from '@/components/Services'
import TopSection from '@/components/TopSection'
import Video from '@/components/Video'
import Head from 'next/head'


export default function Home() {
  return (
    <>
      <Head>
        <title>OPTS Travel</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='container m-auto pt-5'>
        <TopSection title="Тур по Ташкенту" dsc="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco. . ."/>
        <Services/>
        <CardsSection title="Популярные туры" arr={[1,2,3,4,5]} />
        <Video/>
        <Footer/>
      </main>
    </>
  )
}
