import TopSection from '@/components/TopSection'
import Head from 'next/head'


export default function Home() {
  return (
    <>
      <Head>
        <title>OPTS Travel</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='container m-auto py-5'>
        <TopSection title="Тур по Ташкенту" dsc="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco. . ."/>
      </main>
    </>
  )
}
