import Layout from '@/Layout/Layout'
import CardsSection from '@/components/CardsSection'
import Services from '@/components/Services'
import TopSection from '@/components/TopSection'
import Video from '@/components/Video'
import Head from 'next/head'
import { serverSideTranslations } from 'next-i18next/serverSideTranslations'
import { useTranslation } from 'next-i18next'

export async function getStaticProps({locale}) {
  const res = await fetch("https://main--opts-travel.netlify.app/api/tours", {
    method: "GET"
  })
  const data = await res.json()




  return {
    props: {
      data: data,
      ...(await serverSideTranslations(locale, ["header", "expirience", "footer", "main"])),
    },
  }
}

export default function Home({data}) {

  // const {t} = useTranslation("common")

  return (
    <>
      <Head>
        <title>OPTS Travel</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Layout>
          <TopSection arr={data} isSwiper={true} />
          <Services/>
          <CardsSection title="Популярные туры" arr={[1,2,3,4,5]} />
          <Video/>
        </Layout>
      </main>
    </>
  )
}
